### ISSUE TITLE
Fabric 1.20.1 Crash at launch

### ISSUE THREAD

**Issue by 533kr** [ishikyoo/leavesly#1]
Either version of the mod currently causes my game to fail to launch entirely-it may be a compatibility thing, as I have an awful lot of mods, but I'm not sure how to interpret the error, so I pass it on to you.

The relevant log:
[latest.log](https://github.com/user-attachments/files/17236604/latest.log)

**Comment by ishikyoo** [comment]
Fixed in v1.0.2.
